# Generated by Django 3.2.23 on 2024-01-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250, unique=True)),
                ('Content', models.TextField()),
                ('Category', models.CharField(max_length=150)),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
    ]
